# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import AxisSystemControlService_pb2 as AxisSystemControlService__pb2


class AxisSystemControlServiceStub(object):
    """Feature: Axis System Control Service
    Provides functionality to observe and control the state of an axis system
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnableAxisSystem = channel.unary_unary(
                '/sila2.de.cetoni.motioncontrol.axis.axissystemcontrolservice.v1.AxisSystemControlService/EnableAxisSystem',
                request_serializer=AxisSystemControlService__pb2.EnableAxisSystem_Parameters.SerializeToString,
                response_deserializer=AxisSystemControlService__pb2.EnableAxisSystem_Responses.FromString,
                )
        self.DisableAxisSystem = channel.unary_unary(
                '/sila2.de.cetoni.motioncontrol.axis.axissystemcontrolservice.v1.AxisSystemControlService/DisableAxisSystem',
                request_serializer=AxisSystemControlService__pb2.DisableAxisSystem_Parameters.SerializeToString,
                response_deserializer=AxisSystemControlService__pb2.DisableAxisSystem_Responses.FromString,
                )
        self.ClearFaultState = channel.unary_unary(
                '/sila2.de.cetoni.motioncontrol.axis.axissystemcontrolservice.v1.AxisSystemControlService/ClearFaultState',
                request_serializer=AxisSystemControlService__pb2.ClearFaultState_Parameters.SerializeToString,
                response_deserializer=AxisSystemControlService__pb2.ClearFaultState_Responses.FromString,
                )
        self.Get_AvailableAxes = channel.unary_unary(
                '/sila2.de.cetoni.motioncontrol.axis.axissystemcontrolservice.v1.AxisSystemControlService/Get_AvailableAxes',
                request_serializer=AxisSystemControlService__pb2.Get_AvailableAxes_Parameters.SerializeToString,
                response_deserializer=AxisSystemControlService__pb2.Get_AvailableAxes_Responses.FromString,
                )
        self.Subscribe_AxisSystemState = channel.unary_stream(
                '/sila2.de.cetoni.motioncontrol.axis.axissystemcontrolservice.v1.AxisSystemControlService/Subscribe_AxisSystemState',
                request_serializer=AxisSystemControlService__pb2.Subscribe_AxisSystemState_Parameters.SerializeToString,
                response_deserializer=AxisSystemControlService__pb2.Subscribe_AxisSystemState_Responses.FromString,
                )
        self.Subscribe_AxesInFaultState = channel.unary_stream(
                '/sila2.de.cetoni.motioncontrol.axis.axissystemcontrolservice.v1.AxisSystemControlService/Subscribe_AxesInFaultState',
                request_serializer=AxisSystemControlService__pb2.Subscribe_AxesInFaultState_Parameters.SerializeToString,
                response_deserializer=AxisSystemControlService__pb2.Subscribe_AxesInFaultState_Responses.FromString,
                )


class AxisSystemControlServiceServicer(object):
    """Feature: Axis System Control Service
    Provides functionality to observe and control the state of an axis system
    """

    def EnableAxisSystem(self, request, context):
        """Enable Axis System
        Set all axes of the axis system into enabled state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableAxisSystem(self, request, context):
        """Disable Axis System
        Set all axes of the axis system into disabled state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearFaultState(self, request, context):
        """Clear Fault State
        Clears the fault condition of all axes. This is some kind of error acknowledge that clears the last fault and sets the
        device in an error-free state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get_AvailableAxes(self, request, context):
        """Available Axes
        The names of the individual axes of the axis system.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe_AxisSystemState(self, request, context):
        """Axis System State
        The current state of the axis system. This is either 'Enabled' or 'Disabled'. Only if the state is 'Enabled', the axis
        system can move.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe_AxesInFaultState(self, request, context):
        """Axes In Fault State
        Returns all axes of the system that are currently in fault state. The fault state of all axes can be cleared by calling
        ClearFaultState.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AxisSystemControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnableAxisSystem': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableAxisSystem,
                    request_deserializer=AxisSystemControlService__pb2.EnableAxisSystem_Parameters.FromString,
                    response_serializer=AxisSystemControlService__pb2.EnableAxisSystem_Responses.SerializeToString,
            ),
            'DisableAxisSystem': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableAxisSystem,
                    request_deserializer=AxisSystemControlService__pb2.DisableAxisSystem_Parameters.FromString,
                    response_serializer=AxisSystemControlService__pb2.DisableAxisSystem_Responses.SerializeToString,
            ),
            'ClearFaultState': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearFaultState,
                    request_deserializer=AxisSystemControlService__pb2.ClearFaultState_Parameters.FromString,
                    response_serializer=AxisSystemControlService__pb2.ClearFaultState_Responses.SerializeToString,
            ),
            'Get_AvailableAxes': grpc.unary_unary_rpc_method_handler(
                    servicer.Get_AvailableAxes,
                    request_deserializer=AxisSystemControlService__pb2.Get_AvailableAxes_Parameters.FromString,
                    response_serializer=AxisSystemControlService__pb2.Get_AvailableAxes_Responses.SerializeToString,
            ),
            'Subscribe_AxisSystemState': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe_AxisSystemState,
                    request_deserializer=AxisSystemControlService__pb2.Subscribe_AxisSystemState_Parameters.FromString,
                    response_serializer=AxisSystemControlService__pb2.Subscribe_AxisSystemState_Responses.SerializeToString,
            ),
            'Subscribe_AxesInFaultState': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe_AxesInFaultState,
                    request_deserializer=AxisSystemControlService__pb2.Subscribe_AxesInFaultState_Parameters.FromString,
                    response_serializer=AxisSystemControlService__pb2.Subscribe_AxesInFaultState_Responses.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sila2.de.cetoni.motioncontrol.axis.axissystemcontrolservice.v1.AxisSystemControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AxisSystemControlService(object):
    """Feature: Axis System Control Service
    Provides functionality to observe and control the state of an axis system
    """

    @staticmethod
    def EnableAxisSystem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sila2.de.cetoni.motioncontrol.axis.axissystemcontrolservice.v1.AxisSystemControlService/EnableAxisSystem',
            AxisSystemControlService__pb2.EnableAxisSystem_Parameters.SerializeToString,
            AxisSystemControlService__pb2.EnableAxisSystem_Responses.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisableAxisSystem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sila2.de.cetoni.motioncontrol.axis.axissystemcontrolservice.v1.AxisSystemControlService/DisableAxisSystem',
            AxisSystemControlService__pb2.DisableAxisSystem_Parameters.SerializeToString,
            AxisSystemControlService__pb2.DisableAxisSystem_Responses.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearFaultState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sila2.de.cetoni.motioncontrol.axis.axissystemcontrolservice.v1.AxisSystemControlService/ClearFaultState',
            AxisSystemControlService__pb2.ClearFaultState_Parameters.SerializeToString,
            AxisSystemControlService__pb2.ClearFaultState_Responses.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get_AvailableAxes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sila2.de.cetoni.motioncontrol.axis.axissystemcontrolservice.v1.AxisSystemControlService/Get_AvailableAxes',
            AxisSystemControlService__pb2.Get_AvailableAxes_Parameters.SerializeToString,
            AxisSystemControlService__pb2.Get_AvailableAxes_Responses.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe_AxisSystemState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/sila2.de.cetoni.motioncontrol.axis.axissystemcontrolservice.v1.AxisSystemControlService/Subscribe_AxisSystemState',
            AxisSystemControlService__pb2.Subscribe_AxisSystemState_Parameters.SerializeToString,
            AxisSystemControlService__pb2.Subscribe_AxisSystemState_Responses.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe_AxesInFaultState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/sila2.de.cetoni.motioncontrol.axis.axissystemcontrolservice.v1.AxisSystemControlService/Subscribe_AxesInFaultState',
            AxisSystemControlService__pb2.Subscribe_AxesInFaultState_Parameters.SerializeToString,
            AxisSystemControlService__pb2.Subscribe_AxesInFaultState_Responses.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
