"""
________________________________________________________________________

:PROJECT: SiLA2_python

*Axis System Position Controller*

:details: AxisSystemPositionController:
    Allows to control the position of an axis system

:file:    AxisSystemPositionController_real.py
:authors: Florian Meinicke

:date: (creation)          2020-12-15T07:50:56.826849
:date: (last modification) 2020-12-15T07:50:56.826849

.. note:: Code generated by sila2codegenerator 0.2.0

________________________________________________________________________

**Copyright**:
  This file is provided "AS IS" with NO WARRANTY OF ANY KIND,
  INCLUDING THE WARRANTIES OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

  For further Information see LICENSE file that comes with this distribution.
________________________________________________________________________
"""

__version__ = "0.1.0"

# import general packages
import logging
from os import X_OK
import time         # used for observables
import uuid         # used for observables
import grpc         # used for type hinting only
from collections import namedtuple

# import SiLA2 library
import sila2lib.framework.SiLAFramework_pb2 as silaFW_pb2

# import SiLA errors
from impl.common.qmix_errors import SiLAFrameworkError, SiLAFrameworkErrorType

# import gRPC modules for this feature
from .gRPC import AxisSystemPositionController_pb2 as AxisSystemPositionController_pb2
# from .gRPC import AxisSystemPositionController_pb2_grpc as AxisSystemPositionController_pb2_grpc

# import default arguments
from .AxisSystemPositionController_default_arguments import default_dict

from qmixsdk.qmixmotion import Axis, AxisSystem
from qmixsdk import qmixbus

class Position:
    """
    Helper class that defines a simple (X, Y) position vector
    """

    def __init__(self, x: float, y: float):
        """
        Class initializer

        :param x: The X coordinate of the position
        :param y: The Y coordinate of the position
        """
        self.x = x
        self.y = y

    def __str__(self) -> str:
        return "Position({x}, {y})".format(x=self.x, y=self.y)

# noinspection PyPep8Naming,PyUnusedLocal
class AxisSystemPositionControllerReal:
    """
    Implementation of the *Axis System Position Controller* in *Real* mode
        Allows to control motion systems like axis systems
    """

    def __init__(self, axis_system: AxisSystem):
        """
        Class initialiser.

        :param axis_system: The axis system that this feature shall operate on
        """

        self.axis_system = axis_system
        self.movement_uuid = ''

        logging.debug('Started server in mode: {mode}'.format(mode='Real'))

    def _ensure_stopped(self):
        """
        Checks if the axis system is currently moving and if so, stops all movement.
        """
        if self.movement_uuid:
            self.StopMoving(None, None)

    def _validate_uuid(self, uuid: silaFW_pb2.CommandExecutionUUID, check_premature_call = False):
        """
        Checks the given UUID for validity (i.e. if this is the UUID of the current
        movement command) and raises a SiLAFrameworkError if the UUID is not valid.
        Additionally, if `check_premature_call` is set to `True` then it is also
        checked that the axis system is not moving (this is only useful for
        `..._Result` functions). If this check fails, the corresponding FrameworkError
        will be raised, as well.

        :param uuid: The UUID to check
        :param check_premature_call: Whether to check if the axis system is still
                                     moving and raise an error if it is.
        """
        # catch invalid CommandExecutionUUID:
        if not uuid and self.movement_uuid != uuid:
            raise SiLAFrameworkError(
                SiLAFrameworkErrorType.INVALID_COMMAND_EXECUTION_UUID
            )

        # catch premature command call
        if check_premature_call and not self.axis_system.is_target_position_reached():
            raise SiLAFrameworkError(
                SiLAFrameworkErrorType.COMMAND_EXECUTION_NOT_FINISHED
            )

    def _wait_movement_finished(self):
        """
        The function waits until the last movement command has finished
        """

        is_moving = True
        while is_moving:
            time.sleep(0.5)
            logging.info("Position: %s", self.axis_system.get_actual_position_xy())
            yield silaFW_pb2.ExecutionInfo(
                commandStatus=silaFW_pb2.ExecutionInfo.CommandStatus.running
            )
            is_moving = not self.axis_system.is_target_position_reached()

        if not is_moving:
            yield silaFW_pb2.ExecutionInfo(
                commandStatus=silaFW_pb2.ExecutionInfo.CommandStatus.finishedSuccessfully
            )
        else:
            yield silaFW_pb2.ExecutionInfo(
                commandStatus=silaFW_pb2.ExecutionInfo.CommandStatus.finishedWithError
            )
            logging.error("An unexpected error occurred: %s", self.axis_system.read_last_error())

    def MoveToPosition(self, request, context: grpc.ServicerContext) \
            -> silaFW_pb2.CommandConfirmation:
        """
        Executes the observable command "Move To Position"
            Move the axis system to the given position with a certain velocity

        :param request: gRPC request containing the parameters passed:
            request.Position (Position): The position to move to
            request.Velocity (Velocity): A real value between 0 (exclusive) and 1 (inclusive) defining the relative speed at which all axes of the axis system should move.The velocity value is multiplied with the maximum velocity value of each axis. So a value of 1 means, all axes travel with their maximum velocity. A value of 0.5 means, all axes travel with the half of the maximum velocity.
        :param context: gRPC :class:`~grpc.ServicerContext` object providing gRPC-specific information

        :returns: A command confirmation object with the following information:
            commandId: A command id with which this observable command can be referenced in future calls
            lifetimeOfExecution: The (maximum) lifetime of this command call.
        """

        requested_position = Position(
            request.Position.Position.X.value,
            request.Position.Position.Y.value
        )
        requested_velocity = request.Velocity.value

        self._ensure_stopped()

        self.movement_uuid = str(uuid.uuid4())
        command_uuid = silaFW_pb2.CommandExecutionUUID(value=self.movement_uuid)

        self.axis_system.move_to_postion_xy(requested_position.x, requested_position.y, requested_velocity)
        logging.info(f"Started moving to {requested_position} with {requested_velocity*100}% of max velocity")

        # respond with UUID and lifetime of execution
        return silaFW_pb2.CommandConfirmation(
            commandExecutionUUID=command_uuid
        )

    def MoveToPosition_Info(self, request, context: grpc.ServicerContext) \
            -> silaFW_pb2.ExecutionInfo:
        """
        Returns execution information regarding the command call :meth:`~.MoveToPosition`.

        :param request: A request object with the following properties
            commandId: The UUID of the command executed.
        :param context: gRPC :class:`~grpc.ServicerContext` object providing gRPC-specific information

        :returns: An ExecutionInfo response stream for the command with the following fields:
            commandStatus: Status of the command (enumeration)
            progressInfo: Information on the progress of the command (0 to 1)
            estimatedRemainingTime: Estimate of the remaining time required to run the command
            updatedLifetimeOfExecution: An update on the execution lifetime
        """
        # Get the UUID of the command
        self._validate_uuid(request.value)

        logging.info("Requested MoveToPosition_Info for movement (UUID: %s)", request.value)
        logging.info("Current movement is UUID: %s", self.movement_uuid)

        return self._wait_movement_finished()

    def MoveToPosition_Result(self, request, context: grpc.ServicerContext) \
            -> AxisSystemPositionController_pb2.MoveToPosition_Responses:
        """
        Returns the final result of the command call :meth:`~.MoveToPosition`.

        :param request: A request object with the following properties
            CommandExecutionUUID: The UUID of the command executed.
        :param context: gRPC :class:`~grpc.ServicerContext` object providing gRPC-specific information

        :returns: The return object defined for the command with the following fields:
            EmptyResponse (Empty Response): An empty response data type used if no response is required.
        """

        # Get the UUID of the command
        self._validate_uuid(request.value, check_premature_call=True)

        logging.info("Finished moving! (UUID: %s)", self.movement_uuid)
        self.movement_uuid = ''
        time.sleep(0.6)

        return AxisSystemPositionController_pb2.MoveToPosition_Responses()


    def MoveToHomePosition(self, request, context: grpc.ServicerContext) \
            -> AxisSystemPositionController_pb2.MoveToHomePosition_Responses:
        """
        Executes the unobservable command "Move To Home Position"
            Move the axis system to its home position. The axis system should manage the order of the movement and should know how to move all axis into a home state.

        :param request: gRPC request containing the parameters passed:
            request.EmptyParameter (Empty Parameter): An empty parameter data type used if no parameter is required.
        :param context: gRPC :class:`~grpc.ServicerContext` object providing gRPC-specific information

        :returns: The return object defined for the command with the following fields:
            EmptyResponse (Empty Response): An empty response data type used if no response is required.
        """

        self._ensure_stopped()

        self.axis_system.find_home()

        is_moving = True
        while is_moving:
            time.sleep(0.5)
            logging.info("Position: %s", self.axis_system.get_actual_position_xy())
            is_moving = not self.axis_system.is_homing_position_attained()

        return AxisSystemPositionController_pb2.MoveToHomePosition_Responses()


    def StopMoving(self, request, context: grpc.ServicerContext) \
            -> AxisSystemPositionController_pb2.StopMoving_Responses:
        """
        Executes the unobservable command "Stop Moving"
            Immediately stops all movement of the axis system

        :param request: gRPC request containing the parameters passed:
            request.EmptyParameter (Empty Parameter): An empty parameter data type used if no parameter is required.
        :param context: gRPC :class:`~grpc.ServicerContext` object providing gRPC-specific information

        :returns: The return object defined for the command with the following fields:
            EmptyResponse (Empty Response): An empty response data type used if no response is required.
        """

        self.axis_system.stop_move()

        return AxisSystemPositionController_pb2.StopMoving_Responses()


    def Subscribe_Position(self, request, context: grpc.ServicerContext) \
            -> AxisSystemPositionController_pb2.Subscribe_Position_Responses:
        """
        Requests the observable property Position
            The current XY position of the axis system

        :param request: An empty gRPC request object (properties have no parameters)
        :param context: gRPC :class:`~grpc.ServicerContext` object providing gRPC-specific information

        :returns: A response object with the following fields:
            Position (Position): The current XY position of the axis system
        """

        while True:
            position = self.axis_system.get_actual_position_xy()

            yield AxisSystemPositionController_pb2.Subscribe_Position_Responses(
                Position=AxisSystemPositionController_pb2.DataType_Position(
                    Position=AxisSystemPositionController_pb2.DataType_Position.Position_Struct(
                        X=silaFW_pb2.Real(value=position.x),
                        Y=silaFW_pb2.Real(value=position.y)
                    )
                )
            )
            time.sleep(0.5) # give client some time to catch up
