"""
________________________________________________________________________

:PROJECT: sila_cetoni

*Axis System Position Controller_defined_errors*

:details: AxisSystemPositionController Defined SiLA Error factories:
    Allows to control the position of an axis system

:file:    AxisSystemPositionController_defined_errors.py
:authors: Florian Meinicke

:date: (creation)          2021-07-09T10:33:23.529798
:date: (last modification) 2021-07-09T10:33:23.529798

.. note:: Code generated by sila2codegenerator 0.3.6

________________________________________________________________________

**Copyright**:
  This file is provided "AS IS" with NO WARRANTY OF ANY KIND,
  INCLUDING THE WARRANTIES OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

  For further Information see LICENSE file that comes with this distribution.
________________________________________________________________________
"""

__version__ = "0.1.0"

# import general packages
from sila2lib.error_handling.server_err import SiLAExecutionError

# SiLA Defined Error factories

class MovementBlockedError(SiLAExecutionError):
    """
    The movement of the axis system is blocked and rotation is not allowed.
    Rotation is only allowed if the upper limit sensor is on - that means if the
    lift axis is in its topmost position.
    """

    def __init__(self, extra_message: str = ""):
        """
        :param extra_message: extra message, that can be added to the default message
        :returns: SiLAExecutionError
        """

        msg = f"The movement of the axis system is blocked and rotation is not allowed. "\
               "Rotation is only allowed if the upper limit sensor is on - that means if " \
               "the lift axis is in its topmost position." \
               + f'\n{extra_message}' if extra_message else ""
        super().__init__(error_identifier="de.cetoni/motioncontrol.axis/AxisSystemPositionController/v1/DefinedError/MovementBlocked",
                         msg=msg)

